sudo: required
services:
  - docker

before_install:
  - docker build -t zackondocker/react-on-docker -f Dockerfile.dev .

script:
  - docker run zackondocker/react-on-docker npm run test -- --coverage
