sudo: required
services:
  - docker

before_install:
  - docker build -t zackondocker/react-on-docker -f Dockerfile.dev .

script:
  - unbuffer julia --color=yes test/runtests.jl
  - docker run zackondocker/react-on-docker npm run test -- --coverage

addons:
  apt:
    packages:
      - expect-dev # for unbuffer
