sudo: required
services:
  - docker

before_install:
  - docker build -t zackondocker/react-on-docker -f Dockerfile.dev .

script:
  - docker run -e CI=true zackondocker/react-on-docker npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'react-docker'
  env: 'ReactDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-2-725209754350'
  bucket_path: 'react-docker'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: '$AWS_SECRET_KEY'
